version: '3'

services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
      target: ${NODE_ENV:-development}
      args:
        NODE_ENV: ${NODE_ENV:-development}
        NODE_MAJOR_VERSION: ${NODE_MAJOR_VERSION:-18}
    environment:
      NODE_ENV: ${NODE_ENV:-development}
    ports:
      - 3000:3000
