version: '3'

services:
  app:
    volumes:
      - .:/home/node/workspace
      - node_modules_volume:/home/node/workspace/node_modules
    ports:
      - 24678:24678
    tty: true

volumes:
  node_modules_volume:
